apiVersion: batch/v1
kind: Job 
metadata:
  name: {{ include "hello-qa.name" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  template:
    metadata:
      labels:
        app: {{ include "hello-qa.name" . }}
    spec:
      restartPolicy: {{ .Values.restartPolicy }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.global.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["entrypoint.sh"]
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }} 

